### PR TITLE
fix: update electron

### PR DESCRIPTION
**Pull request by daiyam**
This PR is looking to fix a drag-n-drop issue on Wayland.

References:
- #1842

### CODE REVIEW

**Comment by daiyam** [comment]
@lex-ibm @darkyzhou Can you build electron `v32.2.7` for your arch? Thx

**Comment by lex-ibm** [comment]
On it

**Comment by darkyzhou** [comment]
Done, sorry about being late, I was fixing some tricky building issues.

**Comment by lex-ibm** [comment]
https://github.com/lex-ibm/electron-ppc64le-build-scripts/releases/tag/v32.2.7

**Comment by darkyzhou** [comment]
Will you release it soon?

I am rebuilding `32.2.7` with Deepin on LoongArch which offers an older and more stable building environment, can you wait for me to re-upload the artifacts?

**Comment by darkyzhou** [comment]
Done, I've adjusted the Loong64 binaries for version 32.2.7 to require glibc>=2.38 (previously 2.39). This change improves compatibility with more Loong64 distributions.

The build agent images are functioning well and produce binaries with glibc>=2.38 dependency, while I might also update them to base on deepin instead of Debian Trixie.

**Comment by daiyam** [comment]
[1.96.0.24343-insider](https://github.com/VSCodium/vscodium-insiders/releases/tag/1.96.0.24343-insider) is available.

**Comment by lex-ibm** [comment]
Should we have some sort of SIG for ports to other architectures?

**Pull request merged**
