### PR TITLE
New light-colored macOS icon, consistent with logo on other platforms

### PR DESCRIPTION
**Pull request by morellam-dev**
Related to #763. I think the current macOS icon is an interesting design, but I don't like how different it is from the icons on other platforms, and I personally prefer the lighter colors from the Linux/Windows icon. With that in mind, I created this alternative which is identical, except the background is a rounded rectangle.

Current icon:
Current VSCodium icon

Alternative icon:
Redesigned VSCodium icon

This PR simply replaces src/resources/darwin/code.icns with this new icon, scaled down to 512px and converted using libicns.

### CODE REVIEW

**Review by pmahend1 — CHANGES_REQUESTED** [review]
I think you missed few places , for Linux .
I really dont know which ones are used for Linux, except  `letterpress*` are not obviously used. On Ubuntu it shows as green icon on its app store .

```
vscodium\icons\codium_only.svg
vscodium\src\src\vs\workbench\browser\media\code-icon.svg
vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress-dark.svg
vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress-hc.svg
vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress.svg
vscodium\src\resources\linux\code.png
vscodium\src\resources\linux\rpm\code.xpm
```

**Comment by daiyam** [comment]
The following files must not be updated.
```
vscodium\icons\codium_only.svg
vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress-dark.svg
vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress-hc.svg
vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress.svg
```

**Comment by hazarek** [comment]
Voting was held and the blue one was chosen. You cannot change it without voting again.

**Comment by pmahend1** [comment]
@hazarek Could you please link the voting results link here?

**Comment by morellam-dev** [comment]
@pmahend1 Presumably referring to the vote here: #591. I’m only a user of this project, so I wasn’t aware of that discussion till now.

As @h0adp0re said then, the only choices presented were 👍 (use the dark icon, which follows the Big Sur “rounded square” guidelines), or 👎(keep the circular light icon, which doesn’t). No option was presented to simply expand the light icon into a rounded square, so that’s what I’ve done here.

With all due respect @hazarek, I understand that you designed this icon, and are quite attached to keeping it. But as a user on several platforms, I would much rather if macOS used the “official” Codium icon, for consistency’s sake. You’re free to use whatever design you want on your own system, but it feels natural to use what is inarguably the “default” design by default.

I’m interested in what @stripedpajamas thinks of this. Is this something that should be put to another popular vote?

**Comment by pmahend1** [comment]
Thank @morellam-dev 

I personally prefer the blue back-grounded icon . But providing just 👍🏻 and 👎🏻  to vote without much explanation seems like incorrect way to poll. People tend to use 👍🏻 since they are more familiar with that , people dont usually use 👎🏻 unless they really want to criticize something on online. Could have used a third party tool like google forms or something.

If blue backgrounded is preferred then Windows and Linux icons need to be updated.

**Comment by hazarek** [comment]
@morellam-dev 
This is an issue about macOS dark and light mode. Icon with white background causes eye strain on macOS dark mode. Also the contrast is very low. Also there is no official logo. This is an open source project. I designed it to match both Dark and Light mode. You should read the details in the related topic.

The two can change dynamically when macOS supports adaptive icons. I don't know if this is possible right now;
https://stackoverflow.com/questions/55529976/macos-mojave-change-app-icon-to-match-dark-light-mode

**Comment by daiyam** [comment]
@morellam-dev Are you using a dark theme/mode? Is this why you would like a lighter icon?

**Comment by morellam-dev** [comment]
@daiyam I sometimes use macOS in dark mode, but it's not really the lightness or darkness that bothers me. It's just that the aesthetics (colors, drop shadows, gradient direction etc.) in the macOS icon are so distinct from the icon in the Windows/Linux builds that it feels disharmonious. I use all three builds pretty frequently, and I just happen to prefer the "white and cyan" version.

From https://github.com/VSCodium/vscodium/issues/4#issuecomment-427070331, it looks like jaredreich actually created a version of the original blue algae icon which has the colors inverted. I mocked up some Big Sur-style derivatives of those (second row), and also a version with the colors darkened to improve contrast, inspired by Hazarek's design (third row). I actually quite like these designs, so I wonder if it's the drop shadow under the emblem that's not appealing to me?

|           | Lite                                                                                                                          | Dark                                                                                                                         |
|-----------|-------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| Icons by jaredreich  https://github.com/VSCodium/vscodium/issues/4#issuecomment-427070331 | rounded light codium icon  | rounded dark codium icon |
| Converted to rounded rectangle  | square light cyan codium icon  | square dark cyan codium icon |
| Darker blue version |  |  |

Files here: [codium-sur-icons.zip](https://github.com/VSCodium/vscodium/files/7274918/codium-sur-icons.zip). At the very least, these might be useful for people to use as alternative icons on Big Sur.

**Comment by pmahend1** [comment]
If white icon causes strain and not conform to accessibility thresholds then there is no need to keep it on Linux and Windows.
@hazarek Right? 
I personally use VSCodium on both Windows and Mac everyday, both are set on Dark mode. So having two different icons is not consistent. I believe icon should be theme agnostic. Personally using white back-grounded icon is flashy on dark mode for me as well. 
@morellam-dev  I also suggest adding border of 1-2px thickness of different color than the background, to help differentiate if the OS toolbar is pure white or pure blue.

@daiyam IMO its good to have another poll to accommodate opinions

**Comment by hazarek** [comment]
> If white icon causes strain and not conform to accessibility thresholds then there is no need to keep it on Linux and Windows. @hazarek Right? I personally use VSCodium on both Windows and Mac everyday, both are set on Dark mode. So having two different icons is not consistent. I believe icon should be theme agnostic. Personally using white back-grounded icon is flashy on dark mode for me as well. @morellam-dev I also suggest adding border of 1-2px thickness of different color than the background, to help differentiate if the OS toolbar is pure white or pure blue.
> 
> @daiyam IMO its good to have another poll to accommodate opinions

I think the icons on the right are suitable for windows, linux and mac. I think the official icon should be changed to white on blue. I have no problem with the blue ones.

**Comment by aphive** [comment]
I am just now learning of this project, I like the light color background icon but I think that the design itself is way too busy with all the little bulby ends.

**Comment by stech11845** [comment]
> I think you missed few places , for Linux . I really dont know which ones are used for Linux, except `letterpress*` are not obviously used. On Ubuntu it shows as green icon on its app store .
> 
> ```
> vscodium\icons\codium_only.svg
> vscodium\src\src\vs\workbench\browser\media\code-icon.svg
> vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress-dark.svg
> vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress-hc.svg
> vscodium\src\src\vs\workbench\browser\parts\editor\media\letterpress.svg
> vscodium\src\resources\linux\code.png
> vscodium\src\resources\linux\rpm\code.xpm
> ```

We are not talking about Linux here, we're talking about MacOS.

**Comment by GitMensch** [comment]
That should be solved together with https://github.com/VSCodium/vscodium/discussions/1218, which also includes the next, more fine grained voting (I _think_ we're still in the discussion phase), no?
Would there be a reason to have a separate variant for MacOS and/or should there be a light and dark mode version in general (possibly best to be discussed in the related issue)?

**Comment by daiyam** [comment]
@GitMensch They should be same on all platform.

**Comment by GitMensch** [comment]
With or without a secondary set for dark mode?

**Comment by daiyam** [comment]
> With or without a secondary set for dark mode?

A secondary set if it can be done.

**Comment by dionsaur84** [comment]
-1

i prefer the current icon

tired of all these white background icons for everything

**Comment by daiyam** [comment]
Closing due to:
- https://github.com/VSCodium/vscodium/discussions/1429
- https://github.com/VSCodium/vscodium/discussions/1430

**Pull request closed without merging**
