### PR TITLE
feat: automate winget release

### PR DESCRIPTION
**Pull request by daiyam**

### CODE REVIEW

**Comment by daiyam** [comment]
@GitMensch @vedantmgoyal2009 I'm preparing to re-enable the `winget` job with additional checks if it needs to run or not.

**Comment by vedantmgoyal2009** [comment]
* Once https://github.com/microsoft/winget-pkgs/pull/80000 is merged, we can merge this 🎉 Thanks @daiyam.

**Comment by daiyam** [comment]
@vedantmgoyal2009 Thanks for your patience

**Comment by GitMensch** [comment]
So I guess we'd have to wait until the next release before adjusting https://github.com/VSCodium/vscodium.github.io/blob/master/_posts/2000-01-05-install.md, correct? @daiyam Would you mind creating a PR with the necessary changes already?

**Pull request merged**
