### PR TITLE
update icon paths within vscode source

### PR DESCRIPTION
**Pull request by Oekn5w**
Fixes (hopefully) #406 

This is based on the git diff command in the `vscode` repository

````
git diff --name-status 1.44.0 HEAD *.{svg,ico,png}
````

I don't have a development environment set up, I count on the PR build.

Edit: `git diff` output for clarity with PR changes in --><--:
````
D       extensions/markdown-language-features/media/preview-right-dark.svg
D       extensions/markdown-language-features/media/preview-right-light.svg
D       extensions/markdown-language-features/media/view-source-dark.svg
D       extensions/markdown-language-features/media/view-source-light.svg
A       extensions/npm/images/code.svg
D       src/vs/base/browser/ui/menu/menu.svg
D       src/vs/editor/browser/widget/media/diagonal-fill.png
D       src/vs/workbench/api/browser/media/test.svg
-->R100    src/vs/workbench/browser/parts/titlebar/media/code-icon.svg     src/vs/workbench/browser/media/code-icon.svg <--
D       src/vs/workbench/contrib/extensions/browser/media/defaultIcon.png
D       src/vs/workbench/contrib/preferences/browser/media/preferences-editor-dark.svg
D       src/vs/workbench/contrib/preferences/browser/media/preferences-editor-light.svg
-->D       src/vs/workbench/contrib/update/browser/media/code-icon.svg <--
D       src/vs/workbench/contrib/userDataSync/browser/media/check-dark.svg
D       src/vs/workbench/contrib/userDataSync/browser/media/check-light.svg
-->D       src/vs/workbench/contrib/welcome/code-icon.svg <--
R100    src/vs/base/test/node/encoding/fixtures/some.json.png   src/vs/workbench/services/textfile/test/node/encoding/fixtures/some.json.png
R100    src/vs/base/test/node/encoding/fixtures/some.xml.png    src/vs/workbench/services/textfile/test/node/encoding/fixtures/some.xml.png
````

### CODE REVIEW

**Comment by Oekn5w** [comment]
Yes, working on linux x64:

image

**Comment by stripedpajamas** [comment]
Thanks so much for finding this @Oekn5w ... we actually are in the process of switching to a different icon as a part of #413 . I will mention this path there to see if we can knock out two issues at once.

**Comment by Oekn5w** [comment]
@stripedpajamas I think this will also solve the Windows icon, can you please check this in your dev env?

**Comment by stripedpajamas** [comment]
will do!

**Comment by Oekn5w** [comment]
Closing this, as Windows also seems to work according to [comment in #413](https://github.com/VSCodium/vscodium/pull/413#issuecomment-658933404).

Perhaps the workflow here can still help in future issues.

**Comment by Oekn5w** [comment]
Seeing as #582 reverted the logo change, I'll reopen this. @stripedpajamas please review against the current code base

**Comment by stripedpajamas** [comment]
Thanks for reopening, @Oekn5w. I will try building the PR against my branch and check the resulting Windows artifacts.

**Comment by Oekn5w** [comment]
@stripedpajamas What's the status on this?

**Comment by stripedpajamas** [comment]
Sorry for the long wait @Oekn5w -- I built your branch, just need to open it up on my Windows computer and we can merge this.

**Comment by stripedpajamas** [comment]
Confirmed the welcome icon is correct on Windows builds. Thanks @Oekn5w

**Pull request merged**
