### PR TITLE
add deb-rpm-repo hook

### PR DESCRIPTION
**Pull request by paulcarroty**

### CODE REVIEW

**Comment by paulcarroty** [comment]
@daiyam, can you add Gitlab CI variable from the [repo](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo)?

**Comment by daiyam** [comment]
@paulcarroty, when I look at the Pipeline triggers, on your trigger, I only a very short token (4 characters) while the one I've created starts with `glptt-` and is way longer...
Can you send me your token or use my trigger?

**Comment by paulcarroty** [comment]
@daiyam sure I can, but better create your own for security.

**Comment by daiyam** [comment]
@paulcarroty I've updated the secret with the token you've sent me.

**Comment by daiyam** [comment]
I've also fixed the workflow.

Here the result: https://github.com/VSCodium/vscodium/actions/runs/3215027856/jobs/5255837436

**Comment by paulcarroty** [comment]
@daiyam, yeah, we got it working - `{"status":"created"}` in last 2 CI logs, thx!

**Pull request merged**
