### PR TITLE
change vscodium to codium in debian postinst

### PR DESCRIPTION
**Pull request by PalinuroSec**

### CODE REVIEW

**Comment by PalinuroSec** [comment]
we really need this patch to land in master to re-include vscodium in Parrot OS.
We were forced to temporarily remove it

**Comment by stripedpajamas** [comment]
Sorry about the breakage. I will need to delete the current Linux artifacts and trigger a rebuild for this to take affect.

**Comment by xcorshinex** [comment]
Alright ~

**Comment by PalinuroSec** [comment]
when should we import the new artifacts?

**Comment by stripedpajamas** [comment]
I've just deleted the existing artifacts and the build is running https://travis-ci.com/VSCodium/vscodium/builds/114877809

**Comment by PalinuroSec** [comment]
thank you so much!

**Pull request merged**
