### PR TITLE
Create HOW_TO_BUILD_LOCALLY.md

### PR DESCRIPTION
**Pull request by kreck90**
Answer for https://github.com/VSCodium/vscodium/issues/272 question.

### CODE REVIEW

**Comment by GitMensch** [comment]
Any update on this? moving it to a contrib folder sounds reasonable.

**Comment by GitMensch** [comment]
@stripedpajamas as this is closed without a landing of the file anywhere but I'd like to have the info "somewhere" - What do you think of:

* adding a Wiki (that was possibly discussed before but I did not followed that so I don't know the state) where I can add a page for that
* adding that to the end of DOCS.md with a proper context
* create a new contrib folder, adding the initial file there, possibly reference in DOCS.md

**Comment by daiyam** [comment]
I agree with @GitMensch. Wiki or new doc file are good options.

The `build/build_*` scripts are good start to manually build the project but we need to list the dependencies, add some disclaimers (8Go+ memory, can't be compiled under macOS 10.11, esbuild/go dependency).

Also, I would like to add a section how  to locally build the project in the same environment of Github Actions (can be useful when testing AppImage packaging...)

**Comment by daiyam** [comment]
@GitMensch @stripedpajamas I've published the PR #754 to add some build doc

**Pull request closed without merging**
