### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tyu1996**
Added the "AppImage Option" under "Download/Install".

### CODE REVIEW

**Comment by Blondyna** [comment]
Sylwia Panek

**Comment by stripedpajamas** [comment]
Hi @tyu1996 😄 

Thanks for the README update. I'd rather not explain what AppImages are in the VSCodium README, but rather just note that they are available. Instead of adding a new section for AppImage Option, can you instead add `AppImage` to the list of available x64 Linux install files on [line 96](https://github.com/VSCodium/vscodium/blame/master/README.md#L96)?

**Comment by tyu1996** [comment]
Sure. I have already removed the subsection and added in line 96. Please review.

**Comment by stripedpajamas** [comment]
Thanks so much @tyu1996 👍

**Pull request merged**
