### PR TITLE
patch static binary name

### LINKED ISSUE #509: Error: Cask 'vscodium' conflicts with 'visual-studio-code'.
**Describe the bug**
I'm on Mac and I'm trying to install both **VSCode** and **VSCodium** using [Homebrew](https://brew.sh) and I get the following error:

```sh
➜  ~ brew cask install visual-studio-code
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
odrive

==> Downloading https://update.code.visualstudio.com/1.49.1/darwin/stable
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/eeb0142ac77bb0a08e95a4bdbd0afbaf9b826f77d5bbb9889800ead4ae0260f7--VSCode-darwin-stable.zip
==> Verifying SHA-256 checksum for Cask 'visual-studio-code'.
==> Installing Cask visual-studio-code
==> Moving App 'Visual Studio Code.app' to '/Applications/Visual Studio Code.app'.
==> Linking Binary 'code' to '/usr/local/bin/code'.
🍺  visual-studio-code was successfully installed!
➜  ~ brew cask install vscodium
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
tinymediamanager

Error: Cask 'vscodium' conflicts with 'visual-studio-code'.
➜  ~
```

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I install either one or the other using `brew` command and the other one by downloading directly from the corresponding browser link.
- The only problem is when trying to install both using `brew` commands.
- [x] They can remain both in the same computer and they work pretty well after installing using different ways for both.

**To Reproduce**
1. Go to 'terminal' app.
3. Install [Homebrew](https://brew.sh/)
2. Run either `brew cask install visual-studio-code` or `brew cask install vscodium`
3. Run the other command from above (no matter the order).

**Screenshots**
Screen Shot 2020-09-19 at 12 37 38

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Architecture: x64
 - Version: 10.15.6 (19G73)

### PR DESCRIPTION
**Pull request by daiyam**
This PR is patching the binary name to use `product.applicationName` instead of being static.

It should fix #509.

For #654, it needs further informations.

### CODE REVIEW

**Review by pmahend1 — APPROVED** [review]

**Comment by heresy0-0y** [comment]
please merge this to master <33

**Comment by stripedpajamas** [comment]
This looks good but I'm hesitant to pull in another patch that will have to stay up to date with upstream. Has there already been an issue logged and rejected upstream to do what this PR does?

**Comment by daiyam** [comment]
Here the error I got when installing VSCodium with `brew`:
```
==> Installing Cask vscodium
==> Moving App 'VSCodium.app' to '/Applications/VSCodium.app'
==> Backing App 'VSCodium.app' up to '/usr/local/Caskroom/vscodium/1.53.2/VSCodium.app'
==> Removing App '/Applications/VSCodium.app'
==> Purging files for version 1.53.2 of Cask vscodium
Error: It seems there is already a Binary at '/usr/local/bin/code'.
```

So `brew` is installing VSCodium as `code`.
It seems mostly due to https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vscodium.rb#L15

**Comment by heresy0-0y** [comment]
Screen Shot 2021-03-13 at 5 07 48 PM

after brew uninstalling visual-studio-code .... </3

**Comment by daiyam** [comment]
@heresy0-0y Ya, this PR will fix that error.

**Comment by phatpham9** [comment]
I have the same issue as above ones. Hope this will be merged soon!

**Review by stripedpajamas — APPROVED** [review]
LGTM 🚢

**Comment by stripedpajamas** [comment]
@daiyam can you resolve the conflicts, then we will merge this in.

**Pull request merged**
