### PR TITLE
Add new logo

### PR DESCRIPTION
**Pull request by estatra**
- Added a new logo to the project.
- Size was respected and maintained in every directory which the logo is found.
    - Some icons had asymmetric and inconsistent positions, which was fixed. But some required small positional adjustments in order to not conflict with the central icons on `src/resources/win32` and still preserve the original sizes of each icon element.

### CODE REVIEW

**Comment by estatra** [comment]
Hey @stripedpajamas Just letting you know I recently changed my account name and link (I'm Cristiano Vitorino, author of this PR and designer of the new logo). For current and future credit you can just use "Atra", all my links are updated.

**Comment by stripedpajamas** [comment]
Thanks @estatra !! Sorry (again) for the delay. I'm just going to pull down your changes and build so I can spot-check the finished product. Will merge when I've confirmed!

**Comment by estatra** [comment]
> Thanks @estatra !! Sorry (again) for the delay. I'm just going to pull down your changes and build so I can spot-check the finished product. Will merge when I've confirmed!

Awesome! Let me know if anything needs change/improvement.

**Comment by stripedpajamas** [comment]
I downloaded the built DMG:

- I found the DMG window to have a grainy icon
  image
- I found the taskbar icon to also be grainy:
  image

**Comment by estatra** [comment]
@stripedpajamas Weird. I mirrored the original logos exactly, dimension wise. To me it seams like both the original and my version are too small, the **.icns** file in this case, which is 32x32 pixels. 

- Can you confirm that this doesn't happen with the original? Since the original is the same size, I'm not sure that if I just make it larger will solve the problem.
- Where does the **DMG** dialog box and taskbar icon gets the logo from? What are the paths that the code uses?

asd45

**Comment by stripedpajamas** [comment]
I'm no expert on icon files, but when I get info on the same file from VSCodium main branch (src/resources/darwin/code.icns), my Mac is showing dimensions 1024x1024. Isn't it a thing that different dimensions can be embedded into a single icon file? Again, I'm no expert.

image

**Comment by estatra** [comment]
> I'm no expert on icon files, but when I get info on the same file from VSCodium main branch (src/resources/darwin/code.icns), my Mac is showing dimensions 1024x1024. Isn't it a thing that different dimensions can be embedded into a single icon file? Again, I'm no expert.

Neither am I in **.icns** or **.ico** files. My apologies. I noticed that this is the case for the **.ico** files as well. But since I only used conversion for the **.icns** and never opened it, I didn't noticed the embedded versions. So...

1. Can you please verify for me that the Windows version is working properly, icon wise, since I did a single size only instead of the embedded style for the files on `/vscodium-master/src/resources/win32` **.ico** files.
2. Should I redo the embedded style for Windows version on `/vscodium-master/src/resources/win32`? Should that be the case, it would take me a few days as that is quite some work.
3. Do you want me to do a 1024x1024 single for Mac or an embedded style?

**Comment by Antoine-Derouin** [comment]
The .icns do not contain a single image but a collection. It allows among other things to have a design that adapts to the scale. (I hope I'm not off topic)

**Comment by estatra** [comment]
> The .icns do not contain a single image but a collection.
> 
> It allows among other things to have a design that adapts to the scale.
> 
> (I hope I'm not off topic)

Sure, I got that. I was asking if you wanted just a single large file instead of the embedded. I think you want the same process as the original, I can do that.

There are two approaches for this (scaling):
1. Embedded files, each slice with fixed sizes.
2. A single large file, usually a scalable SVG or a fixed ICNS/ICO.

Both cases should scale automatically and properly downwards. Since I don't know how your scripts or the original VSCode does the processing I assumed the second method, as it is widely used.

Please allow me a few days to redo the **.icns** and **.ico** files with the embedded method.

**Comment by estatra** [comment]
I've found some neat tools on Linux that will make the endeavor faster. Also, there are more icons for macOS that needs fixing, gonna do that. I started working on it and will continue tomorrow, it's very late right now.

My apologies @stripedpajamas The embedded structure totally flew over my head.

**Comment by estatra** [comment]
@stripedpajamas I've found new problems. For example. In the official VSCode repo, on the Windows icon folder, the original **code.ico** file has 3 images embedded, but the VSCodium repo has 4. The **c.ico** on VSCode repo has 9 files, on VSCodium, only 6. These represent different sizes. There are discrepancies everywhere between the two repos, icon wise.

Which repo icon structure should I follow? The Original VSCode one or VSCodium's?

**Comment by stripedpajamas** [comment]
@estatra no worries at all! Thank you so much for all the time and effort you've already put in. In regard to icon structure: follow whatever original VSCode repo has. Our icons were committed 2 years ago and have not changed much since (and people find icons we missed all the time).

**Comment by estatra** [comment]
@stripedpajamas No problem. Since VSCode repo doesn't have internal releases, I'll use the **.zip** from the latest commit, which is [#100941](https://github.com/microsoft/vscode/commit/aa60541db5ff286ad9ffaaa77f55e537045df7ad) from 3 hours ago as reference.

I'll try to get this done as soon as I can, but please allow me a few days to finish.

**Comment by estatra** [comment]
@stripedpajamas Done! Commit ready for review.

#### Changelog
- Properly remade ICNS files.
- Properly remade ICO files.
- Upstream had an icon with wrong/bad alignment. Fixed.
- Added missing icons. Upstream used as base.

**Comment by cristianbote** [comment]
I am really sorry that I'm gonna be off-topic a bit, but y'all rock! 💯 🎉  Been using vscodium for more than 3-4 weeks and everything is bliss! I can't wait to get the new icon! 😃  Looks sooooooo nice!

Keep up the good work!

**Comment by stripedpajamas** [comment]
Alright... looking good. I tested on Windows and most everything looked proper, except I did notice the "titlebar icon" had the old Code - OSS icon:

image

The other icon here (the "Welcome" one)... I think @Oekn5w found where the path to that icon lives in their PR (#440), but that PR uses the old codium icon. @estatra if you have some time, can you include their changes in this PR with the new icon? 

As to the Windows titlebar icon, I'm not sure where it lives in the vscode repo, but it might incidentally be one of the 3 files changes in #440.

**Comment by Oekn5w** [comment]
@estatra I think the Windows icon also uses the one whose path is changed in my PR #440 . I've asked @stripedpajamas to confirm as I lack a Windows development environment

**Comment by estatra** [comment]
@stripedpajamas @Oekn5w Done. Please check if this works and if everything is in order.

**Comment by stripedpajamas** [comment]
Awesome; building it now for testing.

**Comment by stripedpajamas** [comment]
Windows looks good:

image

**Comment by stripedpajamas** [comment]
Mac OS looks good too. I will go ahead and merge this! Thanks for the amazing work (and patience) @estatra !

We should see the new icons in next MS release.

**Comment by estatra** [comment]
> Mac OS looks good too. I will go ahead and merge this! Thanks for the amazing work (and patience) @estatra !
> 
> We should see the new icons in next MS release.

Awesome! My pleasure! It was a fun ride : )

**Comment by geekley** [comment]
@stripedpajamas 
> Alright... looking good. I tested on Windows and most everything looked proper, except I did notice the "titlebar icon" had the old Code - OSS icon:

After the logo reversion, I'm getting the Code-OSS icon in Linux snap as well (Kubuntu, KDE Plasma), instead of a coral icon.
image

**Comment by Oekn5w** [comment]
@geekley see #440, these changes where included in here, I've reopened the PR to fix this

**Pull request merged**
