### PR TITLE
changed hardcoded owner

### PR DESCRIPTION
**Pull request by dsm**
Hi, This may be well for vscodium fork.

### CODE REVIEW

**Comment by GitMensch** [comment]
Where is that variable set?

**Comment by dsm** [comment]
https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

This are github's default env vars and github says that;

"The default environment variables that GitHub sets are available to every step in a workflow.

We strongly recommend that actions use environment variables to access the filesystem rather than using hardcoded file paths. GitHub sets environment variables for actions to use in all runner environments."

**Comment by GitMensch** [comment]
Thank you for the information. Please adjust to pre-calculate two variables - OWNER and REPOSITORY (from the env vars available the first must be removed from the second) with a fallback to the current values - and I'll merge. Thanks.

**Comment by dsm** [comment]
I made this changes available please check it. Thanks

**Comment by daiyam** [comment]
I've moved the variables outside the loop (#1002)

**Pull request merged**
