### PR TITLE
Revert logo change

### LINKED ISSUE #491: [PLEASE VOTE] [Discussion] Icon design and/or configuration should be improved
**Comment hijacked by project maintainer: please vote on the project's icon below: https://github.com/VSCodium/vscodium/issues/491#issuecomment-691597222**

Original issue from @cdata below.

-------

**TL;DR would one or both of the following things be possible:**

 1. Improve the existing icon to have a relatively high contrast ratio across at least as many common contexts as the old logo
 2. Make it possible to easily configure a preferred icon as a matter of editor configuration (so that it follows configuration across installations)

**Background**

Hey y'all, just want to start by saying that I love this project. I use it on all of my machines and benefit greatly from the work that this community has done to support the existence of a relatively liberated, modern code editor.

In https://github.com/VSCodium/vscodium/issues/313, there was some discussion and worthy design ideation around the creation of a new logo. Speaking for myself, I had no idea this discussion was taking place, although it is nice to know that it happened out in the open. As suggested in [this comment](https://github.com/VSCodium/vscodium/issues/313#issuecomment-677454842), I am one of the folks who had no idea this change was happening until I updated.

**Proposal**

I read through the design ideation for the new icon. I think the new icon is okay. However, I also believe that the older icon was better on a couple of dimensions:

 1. Subjectively, the older icon was prettier; I personally find the official VSCode logo to be pretty corporate and blah, but even that logo is subjectively prettier to me. It seems like there is a lot of agreement expressed in https://github.com/VSCodium/vscodium/issues/472
 2. Objectively, the older icon stood out well against a wider range of background colors. Some of this issue is alluded to in https://github.com/VSCodium/vscodium/issues/477

I would like to open the discussion for ways in which the icon could potentially be improved, or perhaps - in the hope of avoiding an impossible bike shed design argument - ways we could make icon customization a little bit easier so that there are more options available to suit users' preferences.

**Humble request**

The decision to change the design seems to have been driven by a single community member's subjective assessment of the icon (note: I only have the context of #313, and I do not know if there was some consensus being driven elsewhere). However, a change like this has a broad impact on the community overall. I hope we can have an open and respectful conversation about this with the goal to keep VSCodium being the best code editor that it can be.

### PR DESCRIPTION
**Pull request by stripedpajamas**
Due to the fact that the recent logo change did not involve a vote, and after the fact an overwhelming majority voted against it, this PR reverts the change.

Closes #491

### CODE REVIEW

**Comment by hazarek** [comment]
The macos icon should be updated for bigsur.

**Comment by jacksongoode** [comment]
Waiting for a big update to make this change?

**Comment by hazarek** [comment]
what are you waiting for?

**Comment by stripedpajamas** [comment]
Will need a vote for big sur icons; will merge this as is for now.

**Comment by baco** [comment]
When will the new logo be effectively voted for yes or for no? I mean, there was a clear candidate voted between 6 alternatives, and I understand that the rollback in the selection was due to the fact that in spite of having a winner there wasn't a vote for the effective change towards the new logo. When will it be?

**Pull request merged**
