### PR TITLE
fix: update to 1.76

### PR DESCRIPTION
**Pull request by daiyam**

### CODE REVIEW

**Comment by GitMensch** [comment]
It will be interesting to see if OpenSSH-Remote still works... ;-)

**Comment by daiyam** [comment]
I will test it on the Insiders. But anyway, the `1.76` will be pushed tomorrow. If the workflows run now, they might create 2 releases... I don't want to try my luck.

**Comment by daiyam** [comment]
I wasn't to compile the project on the Mac mini M1 (which I use to update VSCodium since it's fast). Fixed now.

**Comment by daiyam** [comment]
Building, going to test it in the morning.

**Pull request merged**
