### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @VSCodium.

* Resolves https://github.com/VSCodium/vscodium/issues/1171

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@stripedpajamas releases are now published using a personal access token (PAT) since when the release is published by github-actions:

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. For more information, see "[Authenticating with the GITHUB_TOKEN](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)."

_Source: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow_

This won't trigger the winget workflow: 
image

**Comment by daiyam** [comment]
@vedantmgoyal2009 Hi, thanks for your PR but could you make the following changes:
- at the end of `windows.yml`, add the step from your `winget.yml` with `if: env.SHOULD_BUILD == 'yes' && env.SHOULD_DEPLOY == 'yes'`
- revert to `GITHUB_TOKEN`

`on: release: types: [released]` might not work since the windows binaries are the latest to be published.
If the event is generated when the release is created, `winget.yml` will fail since the binaries aren't there yet...

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009 Hi, thanks for your PR but could you make the following changes:
> 
> * at the end of `windows.yml`, add the step from your `winget.yml` with `if: env.SHOULD_BUILD == 'yes' && env.SHOULD_DEPLOY == 'yes'`
> * revert to `GITHUB_TOKEN`
> 
> [...]

@daiyam I've made the changes since the action has been updated as I'd mention in the previous comment. Please review.

**Comment by daiyam** [comment]
@vedantmgoyal2009 If everything is ok, it should be deployed in about 1 hour...

**Comment by vedantmgoyal2009** [comment]
Thanks. Please fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @VSCodium. It is required since the new manifests will be pushed to the fork and then a PR will be created at microsoft/winget-pkgs which will be approved and merged by the community moderators there.

**Comment by daiyam** [comment]
Ah! I'm not able to do that.

@stripedpajamas Can you fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)?

**Comment by daiyam** [comment]
@vedantmgoyal2009 How do you deal with the different architectures (x64, ia32 or arm64)?

**Comment by vedantmgoyal2009** [comment]
I forgot that the job has a matrix too. Thanks for telling 🙏🏻

**Pull request merged**
