### PR TITLE
Updated with 32-bit support

### LINKED ISSUE #6: ARM packages.
I'm helping with a GPL package manager for Chromebooks, called Chromebrew. It would really help if you could also create i686 and ARM tarballs. Thank you.

### PR DESCRIPTION
**Pull request by JL2210**
Fixes #6

Note: I'm inexperienced in Travis YAML, so feel free to give suggestions!

### CODE REVIEW

**Comment by JL2210** [comment]
Sure.

**Comment by JL2210** [comment]
What are the build dependencies? What is this `npx` command?

**Comment by stripedpajamas** [comment]
It's a separate binary packaged with `npm`: https://github.com/zkat/npx
```bash
$ npx <command>
```
> Executes <command> either from a local node_modules/.bin, or from a central cache, installing any packages needed in order for <command> to run.

**Comment by JL2210** [comment]
OK. Thanks. This might be a good package for chromebrew.

**Comment by stripedpajamas** [comment]
That would be nice-- it is supported in homebrew already

**Comment by JL2210** [comment]
Also, a suggestion: Could we download the tarballs instead of cloning all the history of the repository? It's only on 23% and it's downloaded over 100MB so far.

**Comment by JL2210** [comment]
I don't see it. Do you mean VSCodium? I meant npx.

**Comment by JL2210** [comment]
This needs ARM support before it can be a candidate for Chromebrew.

**Comment by JL2210** [comment]
What system do you build on? I'm having trouble.

**Comment by stripedpajamas** [comment]
I build the Darwin version on my local Mac and I build the Linux version in a Docker container. But then ultimately I push changes up and watch how Travis handles it.

**Comment by JL2210** [comment]
Chromebrew doesn't have Docker yet, so I'll see how this will work on my Chromebook.

**Comment by JL2210** [comment]
It's hung at `[17:17:39] Starting 'minify-vscode'...`

**Comment by stripedpajamas** [comment]
I got the build working after a lot of jumping through hoops -- can you confirm the resulting builds are ok at https://github.com/stripedpajamas/vscodium/releases ? I don't suspect any issues because the builds succeeded without errors. If it looks good I'll put in a PR

**Comment by stripedpajamas** [comment]
See #32 for big code changes that make the builds work. I think this PR can be closed.

**Comment by JL2210** [comment]
Let me double check.

**Pull request closed without merging**
