### PR TITLE
feat(1.95): update patches

### PR DESCRIPTION
**Pull request by daiyam**

### CODE REVIEW

**Comment by daiyam** [comment]
@lex-ibm Hi, I have disabled ppc64 build.
Because the dependency `@vscode/policy-watcher` is using the gcc's flag `-std=gnu++20`, so I have updated to `gcc-10`.
I'm not sure how to update the `sysroot`, if you could do it, it would be great.

**Comment by lex-ibm** [comment]
Roger that, will get this out asap

**Comment by lex-ibm** [comment]
@daiyam I saw the `focal-ppc64le` build failed, but I was able to build it in my local. Was qemu enabled for that job?

**Comment by lex-ibm** [comment]
I believe [this line](https://github.com/VSCodium/vscode-linux-build-agent/blob/bd48b4709943e33404d9db89dbb18511ef581f19/.github/workflows/build.yml#L31) is missing `focal-ppc64le`

**Comment by daiyam** [comment]
> I believe [this line](https://github.com/VSCodium/vscode-linux-build-agent/blob/bd48b4709943e33404d9db89dbb18511ef581f19/.github/workflows/build.yml#L31) is missing `focal-ppc64le`

yep!

**Comment by daiyam** [comment]
From https://github.com/VSCodium/vscodium/actions/runs/11328290273/job/31501917695, it's still using the gcc of the sysroot (gcc-8.5), define in the patch (`export CC=$VSCODE_SYSROOT_DIR/powerpc64le-linux-gnu/bin/powerpc64le-linux-gnu-gcc`).
In #2059, I'm trying to see if we can avoid the sysroot since riscv64 do compile without it.

**Pull request merged**
