### PR TITLE
WIP: feat: attempt to create pipeline for latest insider version

### PR DESCRIPTION
**Pull request by Ranguna**
The latest version of insider is 1.79, but the current version in insider.json is fixed to 1.78.

This PR blindly rebased `insider` on top of `master` and removed the `insider.json` to analyse whether a pipeline would successfully build the latest version of vsode insider.

### CODE REVIEW

**Comment by daiyam** [comment]
`insider.json` is updated by doing `./build/build.sh -il`

**Comment by daiyam** [comment]
The insider version has been updated

**Comment by Ranguna** [comment]
Thanks @daiyam !

I checked the last commits and it seems the aur package wasn't published: https://github.com/VSCodium/vscodium/actions/runs/5106603386/jobs/9179074113

And the latest commit did not trigger a pipeline: https://github.com/VSCodium/vscodium/commit/b019f9c25ad90c3be9f1ffe781467cfbaa787c75

Would it be possible to publish the aur package for the latest commit ?

**Comment by daiyam** [comment]
It has been updated

**Pull request closed without merging**
