### PR TITLE
Dockerfile for image creation for building vscode

### PR DESCRIPTION
**Pull request by tynx**
This first try at a Dockerfile allows to build vscode inside a docker container. I don't know if it's useful for others but wanted to make a PR just in case...

### CODE REVIEW

**Comment by stripedpajamas** [comment]
I like this, and I have something similar in a gist [here](https://gist.github.com/stripedpajamas/e9c90da42f904ede8e158421562ee8f3) which I use when I'm testing things out. But I think having it in this repo where it is not being used will be confusing to people trying to figure out what exactly the vscodium build process involves.

**Comment by mirekphd** [comment]
Time has shown that closing first PR with a Dockerfile was probably misguided...

**Comment by mirekphd** [comment]
Some devs that could help here: 
https://www.reddit.com/r/docker/comments/vl25ao/is_there_a_guide_of_how_to_get_vscodium_on_a/

**Comment by daiyam** [comment]
https://github.com/VSCodium/vscodium/blob/master/docs/build.md#build-docker

**Pull request closed without merging**
