### PR TITLE
build: double quote args to prevent globbing and word splitting

### PR DESCRIPTION
**Pull request by Fdawgs**
Some scripts are already double-quoting args, so this updates the rest to makes it consistent.

### CODE REVIEW

**Comment by daiyam** [comment]
To be consistent, `$UPDATE_INFO` should be replaced with `"${UPDATE_INFO}"`

**Comment by Fdawgs** [comment]
> To be consistent, `$UPDATE_INFO` should be replaced with `"${UPDATE_INFO}"`

Added in https://github.com/VSCodium/vscodium/pull/1105/commits/4e69fb6012c68d80427bd945996cc44c4bb91662

**Comment by daiyam** [comment]
@Fdawgs Thx Sorry, I wasn't clear enough. I was thinking to change all variables...

**Comment by Fdawgs** [comment]
> @Fdawgs Thx Sorry, I wasn't clear enough. I was thinking to change all variables...

Gotcha, think that could be thrown into separate PR?

**Comment by daiyam** [comment]
No, it's ok to make the changes in this PR since it's related to have a consistent use of the variables.

**Comment by Fdawgs** [comment]
> No, it's ok to make the changes in this PR since it's related to have a consistent use of the variables.

Think i've got the remaining ones with https://github.com/VSCodium/vscodium/pull/1105/commits/13a8c30b03302782d42a44b1f5ddcc591db517d9 and https://github.com/VSCodium/vscodium/pull/1105/commits/92e5bda513c08e44e457b99333ffbc0a4640a0e5

**Comment by daiyam** [comment]
Thx

**Pull request merged**
