### PR TITLE
Add support to use GNU sed installed in mac osx

### PR DESCRIPTION
**Pull request by swinder0161**

### CODE REVIEW

**Comment by swinder0161** [comment]
@daiyam Please help to review, this is required is sed is installed from macports or homebrew in mac osx

**Comment by daiyam** [comment]
Can you use the function `is_gnu_sed`  from `https://github.com/VSCodium/vscodium/blob/master/update_settings.sh`? Thx

**Comment by swinder0161** [comment]
@daiyam Wont the function be only visible to the sh file in which it is defined unless export -f is done?

**Comment by swinder0161** [comment]
to get functions at global scope the sh need to be used with source <path to script.sh> but i see the update_settings.sh is called as a sub process
https://github.com/VSCodium/vscodium/blob/master/prepare_vscode.sh#L8

**Comment by daiyam** [comment]
You could move the function in a shared file (like `util.sh`) and import the file with `source "./util.sh"`.

**Comment by swinder0161** [comment]
Ok. All try it tomorrow.

**Comment by daiyam** [comment]
Thx

**Comment by swinder0161** [comment]
Ok, its done now. @daiyam

**Pull request merged**
