### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by pavanagrawal123**
Start of Azure Pipelines for Windows Builds, need release publishing!

### CODE REVIEW

**Comment by stripedpajamas** [comment]
This is looking great @pavanagrawal123 🎉 

Only thing I found online about GH releases is this blog post from @headmelted (who incidentally runs releases for vscode arm builds): https://headmelted.com/continuous-delivery-with-azure-pipelines-and-github-releases-20a0155360d8

Towards the end of the article it looks like he's doing it manually by POSTing to Github's API. We can probably do similarly. 

Is there somewhere we can see the output of your builds? Similar to https://travis-ci.com/VSCodium/vscodium but for Azure pipelines?

**Comment by pavanagrawal123** [comment]
Yep! You can check this link: https://dev.azure.com/pavanagrawal0428/VSCodium/_build/results?buildId=28&view=logs

and click here:
image

**Comment by pavanagrawal123** [comment]
Hey @stripedpajamas I got the release publishing to GH working! 

I was confused though, what release should I be publishing? System setup or user setup? Also what should I name the file?

Thanks

**Comment by stripedpajamas** [comment]
Awesome!! 

Publish everything you have -- system setup, user setup, and zip file. You can probably copy Microsoft's naming convention:

64-bit user setup: `VSCodiumUserSetup-x64-${version}.exe`
64-bit system setup: `VSCodiumSetup-x64-${version}.exe`
64-bit zip file: `VSCodium-win32-x64-${version}.zip`

or something like that :)

**Comment by pavanagrawal123** [comment]
Alright, just published final changes, if all goes well I'll end up with some built packages on my personal branch...

Also, was wondering -> the build seems to take 30 mins for Windows, any way to speed it up?

**Comment by stripedpajamas** [comment]
@pavanagrawal123 nah, 30 mins what it takes on Travis for Linux and OSX too. Just a big bulky build process 🤷‍♂️

**Comment by pavanagrawal123** [comment]
It's working now @stripedpajamas!
image

**Comment by stripedpajamas** [comment]
Yes!!! Ok one more thing. Your check tags script checks for .zip but the Mac file is also a zip file. I think the existing check tags script should be changed to check for a file that contains "darwin" and your check tags script should he changed to look for something unique in the windows zip file name.

**Comment by pavanagrawal123** [comment]
Can we rely on the fact that if there are no .exe files the build should occur?

**Comment by stripedpajamas** [comment]
I suppose that is fine :) This looks good to me. I say we merge it and let the chips fall 👍

**Comment by stripedpajamas** [comment]
@pavanagrawal123 how do we set up this up for VSCodium? I have a feeling there's more to it than just merging. Can you walk me through it?

**Comment by pavanagrawal123** [comment]
@stripedpajamas ahh yes it will def be more than merging.... 
You'll need to you start an account here: https://azure.microsoft.com/en-us/services/devops/pipelines/
and then hook it up to this repo (after merging PR) and then install 2 plugins the yarn one and the github one, and then once you get that, you'll be able to configure the release pipeline. The release pipeline for some reason isn't defined in YAML, but it is pretty simple i can send some screenshots....

Or if this ends up being too much I can also configure it if you can give me access to the Azure Pipelines account you setup....

**Comment by stripedpajamas** [comment]
Screenshots would be great!!

**Comment by pavanagrawal123** [comment]
image

**Comment by kaylangan** [comment]
Looks like you have been able to get things working! Let me know if you have any questions or suggestions. I'm a Program Manager on Azure Pipelines and I'm happy to help!

**Comment by stripedpajamas** [comment]
@kaylangan is there any way around this https://stackoverflow.com/questions/52677708/azure-devops-build-pipeline-unreliable-triggering-by-schedule ?

With Travis, the builds run every day so we can make sure we are up-to-date with the Microsoft repo, but it seems that Azure will not honor our build schedule if someone is not logged in. Doesn't this defeat the purpose of a schedule?

**Comment by kaylangan** [comment]
@stripedpajamas Sorry for the delayed reply. If your repo continues to have commits and you're using the GitHub app or have a CI trigger set up, then the host will stay alive. The host should only go dormant if you're relying only on scheduled triggers _and_ not using the GitHub app. We're looking into a solution to that scenario.

Are you seeing dormancy in other scenarios?

**Comment by stripedpajamas** [comment]
@kaylangan thank you for the reply 🙏

Our build process involves cloning down a different repo (vscode) and building it. So no commits are added to this repo and the only way to know if we _should_ build is by cloning down the other repo (vscode) regularly and checking the version. In Travis we do a scheduled build every day, but it looks like our scheduled trigger in Azure goes dormant. We have #68 to migrate away from Azure unless we can think of something clever 😄

**Comment by kaylangan** [comment]
@stripedpajamas Ah, I understand. There's a workaround that I can think of, but I wouldn't recommend it. That said, we're working on a multi-checkout feature that would fully enable your scenario. With multi-checkout, you'd set the vscode repo as a resource and then trigger builds off changes to vscode rather than your own repo.

**Comment by kaylangan** [comment]
I can't say definitively, but likely on the order of 3-6 months.

**Pull request merged**
