### PR TITLE
Add ability to apply user specific patches to vscode source

### PR DESCRIPTION
**Pull request by swinder0161**
Please help to merge

### CODE REVIEW

**Comment by swinder0161** [comment]
@daiyam help merge this patch as an improvement to the tool scripts

**Review by daiyam — APPROVED** [review]

**Comment by daiyam** [comment]
@stripedpajamas This PR can be useful. Can you merge it?

**Review by stripedpajamas — APPROVED** [review]

**Comment by swinder0161** [comment]
Thanks for merging my first pull request for the project.

I will try to put more value additions for codium going forward.

Since the day I built it and started using it, I am feeling like I am using
my own editor better that vscode I have been using thus far.

My pull request is lying with vscode since 6 months without getting any
feedback from them. I added my patch to codium and build it.

**Comment by daiyam** [comment]
@swinder0161 Welcome to the club :wink: (same issue with vscode)

**Pull request merged**
