### PR TITLE
Add update information to AppImage

### PR DESCRIPTION
**Pull request by zilti**

### CODE REVIEW

**Comment by stripedpajamas** [comment]
Can you explain what this change does? Not too familiar with how app images update. If we need the zsync file included in the GH release, the .travis.yml file would need an update too I think.

**Comment by zilti** [comment]
Sure. Adding the `UPDATE_INFORMATION="gh-releases-zsync|VSCodium|vscodium|latest|*.AppImage.zsync"` environment variable causes the tool to embed that information into the AppImage. The format is `updatetype|organisation|repository|tag|zsyncfile`, and `latest` will cause it to use the newest tag/release. Tools like AppImageUpdate can then update the AppImage.

**Comment by stripedpajamas** [comment]
Awesome, thanks so much for doing this

**Comment by zilti** [comment]
I noticed that the .zsync file does not get added to the release... I am not sure why this happens though, I don't know your release pipeline very well

**Pull request merged**
