### PR TITLE
fixup: remove mangling in extensions/ (introduced in 1.80)

### PR DESCRIPTION
**Pull request by brjsp**
This also fixes the reproducibility issue mentioned in https://github.com/microsoft/vscode/issues/189124

### CODE REVIEW

**Comment by daiyam** [comment]
Is this still an issue after their fix?

**Comment by brjsp** [comment]
Probably isn't. I haven't checked but AFAIK you want to remove mangling anyway to make hacking the UI possible.

I myself don't use UI-changing extensions but have noticed that the mangler often OOMed on our (openSUSE) servers leading to build failures.

**Comment by daiyam** [comment]
The changes have been merged in #2090. We will test it in the Insiders version to see if there is no issues before moving it to the stable version.

**Comment by daiyam** [comment]
@brjsp Thanks for the PR.
Sorry, seeing you have reacted, I could have asked you to make the change. But since it's a more than a year old PR, I didn't think you were still there ;)

**Pull request closed without merging**
