### PR TITLE
use script to generate icons

### LINKED ISSUE #614: Missing Golang icon (go.icns)
**Describe the bug**
Go language document icon (go.icns) is missing in this folder: https://github.com/VSCodium/vscodium/tree/master/src/resources/darwin

my related proposal here. https://github.com/VSCodium/vscodium/discussions/616

### PR DESCRIPTION
**Pull request by daiyam**
This PR adds a script to generate the icons.

It should fix #614 and it can easily updated for #616.

### CODE REVIEW

**Comment by stripedpajamas** [comment]
thanks for putting this together @daiyam. what's the intended use? like do we run once whenever the icon changes and commit the resulting icon sets? or do we run the script at build time?

**Comment by hazarek** [comment]
> thanks for putting this together @daiyam. what's the intended use? like do we run once whenever the icon changes and commit the resulting icon sets? or do we run the script at build time?

run once.  this should only be produced once until the next icon change.

**Comment by stripedpajamas** [comment]
dope. is it merge-ready ? (not sure if it was updated regarding discussion #616 )

**Comment by daiyam** [comment]
Yes, now, it's using the icon from #616.

**Review by stripedpajamas — APPROVED** [review]

**Comment by stripedpajamas** [comment]
Thanks @daiyam and @hazarek

**Comment by yusf** [comment]
Please reopen and do it right, #616 doesn't adhere to macOS standards.

**Comment by hazarek** [comment]
> Please reopen and do it right, #616 doesn't adhere to macOS standards.

https://github.com/VSCodium/vscodium/discussions/616#discussioncomment-357701

**Pull request merged**
