### PR TITLE
feat: add linux riscv64 reh build and fix some ppc64 stuff BTW

### PR DESCRIPTION
**Pull request by kxxt**
This PR adds riscv64 REH builds and fixes some ppc64 code BTW.

Upstream seems to switch to using sysroots but the old approach still works.

Although this PR only adds REH builds,  I am maintaining [a fork of electron for riscv64](https://github.com/riscv-forks/electron) so if desired I can add other types of builds for riscv64 in the future but that will require more patches. https://github.com/riscv-forks/electron-riscv-releases

This PR is currently using `rsworktech/vscodium-linux-build-agent:focal-devtoolset-riscv64`. I need to update it once https://github.com/VSCodium/vscode-linux-build-agent/pull/19 get merged.

### CODE REVIEW

**Comment by daiyam** [comment]
> I need to update it once https://github.com/VSCodium/vscode-linux-build-agent/pull/19 get merged.

Done. I would have asked you to do it anyway.

**Comment by kxxt** [comment]
> > I need to update it once [VSCodium/vscode-linux-build-agent#19](https://github.com/VSCodium/vscode-linux-build-agent/pull/19) get merged.
> 
> Done. I would have asked you to do it anyway.

Thanks for your quick review! I think we need to enable the workflows after the docker images get published.

**Comment by daiyam** [comment]
OK. I will have to change how `check_tags.sh` is working for the first check on Linux. It has to check all archs. I will see that tonight.

**Comment by daiyam** [comment]
It's available in `1.88.1.24104`

**Comment by kxxt** [comment]
> It's available in `1.88.1.24104`

Thanks very much! 😊

**Comment by daiyam** [comment]
By the way, with VSCodium, you will need to use the extension [Open Remote - SSH](https://open-vsx.org/extension/jeanp413/open-remote-ssh) since it's incompatible with VSCode Remote.

**Comment by kxxt** [comment]
> By the way, with VSCodium, you will need to use the extension [Open Remote - SSH](https://open-vsx.org/extension/jeanp413/open-remote-ssh) since it's incompatible with VSCode Remote.

Yes. I have opened a PR to open-remote-ssh as well. It haven't been merged yet. https://github.com/jeanp413/open-remote-ssh/pull/147

**Pull request merged**
