### PR TITLE
build: Use `cd ... || exit` in case `cd` fails

### PR DESCRIPTION
**Pull request by Fdawgs**
Already being done here:

https://github.com/VSCodium/vscodium/blob/98d30bdc2c373068f1409cad1e98709b8c9e6afe/build.sh#L13

### CODE REVIEW

**Comment by paulcarroty** [comment]
I'd suggest to use `cd vscode | { echo "'vscode' dir not found"; exit 1; }`.

**Comment by Fdawgs** [comment]
> I'd suggest to use `cd vscode | { echo "'vscode' dir not found"; exit 1; }`.

Should i update the existing `cd` calls with this also?

**Comment by paulcarroty** [comment]
Not to all for sure, will be nice to get readable errors for the critical events like download/pull/artifact generation failed.

**Comment by Fdawgs** [comment]
> I'd suggest to use `cd vscode || { echo "'vscode' dir not found"; exit 1; }`.

Updated in https://github.com/VSCodium/vscodium/pull/1107/commits/3233ba97c0f37302b7beaca780d9369a34eaafa2

**Comment by Fdawgs** [comment]
> Can you update the existing one? Thx

Sure, tackled in https://github.com/VSCodium/vscodium/pull/1107/commits/22de031fbd19b98560573bdbcd09a5571f6d01ea

**Comment by daiyam** [comment]
Thx

**Pull request merged**
