### PR TITLE
Implement WiX based MSI setup

### PR DESCRIPTION
**Pull request by alexhass**
As requested in https://github.com/VSCodium/vscodium/issues/106 I have build the MSI setup for VSCodium.

This is the first setup version. As I'm new to the project VSCodium I have no good understanding about your file and folder structure. I was quite confused about this total different from VSCode. So I decided to go with the structure of VSCode. I think we need to improve this in further commits.

The only duplicate is code.ico file that is copied from /src/resources/win32/code.ico.

The LICENSE.rtf text is taken over from the base folder LICENSE file. Aside there is a copyright year 2018 inside... that should be fixed in a follow up for both license files, too. Side note - we cannot use the existing text file in the MSI setup - we need an RTF file, so we need to maintain both files.

Additionally this installer can do two things. Per Machine install (default) and per User install in one installer.

The setup needs testing. I will publish an article on my personal website with test builds today/tomorrow and share the link here asap.

**TODO:**

- We need binaries with updates disabled or at least a way to install two different files. One config file with updates disabled and one with updates enabled! In general we can allow both, but enterprise users like me need updates disabled as sysadmins control the update time/date and not a VSCode release manager.

### CODE REVIEW

**Comment by alexhass** [comment]
I guess I’m not reponsible for this test failures.

**Comment by GitMensch** [comment]
> The only duplicate is code.ico file that is copied from /src/resources/win32/code.ico.

It would be good to copy that on-the-fly before starting the creation of the msi.

> The LICENSE.rtf text is taken over from the base folder LICENSE file. Aside there is a copyright year 2018 inside... that should be fixed in a follow up for both license files, too. Side note - we cannot use the existing text file in the MSI setup - we need an RTF file, so we need to maintain both files.

Can we use any utiltily to convert the LICENSE file on the fly? Maybe [textutil]()https://ss64.com/osx/textutil.html `textutil -convert rtf LICENSE`?

> We need binaries with updates disabled or at least a way to install two different files. One config file with updates disabled and one with updates enabled! In general we can allow both, but enterprise users like me need updates disabled as sysadmins control the update time/date and not a VSCode release manager.

I totally agree. See https://github.com/VSCodium/vscodium/issues/106#issuecomment-724326854 for my initial take on how to do that.

**Comment by alexhass** [comment]
> code.ico
I think we do not need to do this. We can change the path to point to the correct file in repro / build paths. I just have no idea about the file / folder structure of the project... it is too flat :-)

If textutil is available on windos this may work. I'm not sure about the line feeds as I removed all and than pasted the text to wordpad. This should not block something... improvements can be done at any time.

I have no idea how to compile the vscodium myself... so no idea how to build two independed configs. I only remember from vscode if I change the file manually vscode collapse with errors as the file is no longer original :-(. So I really need help with further tasks or someone from the maintainers take over from here and integrate all into the build process. That would be best for me. I can help with questions and improvements to my code.

**Comment by paulcarroty** [comment]
@alexhass probably https://github.com/VSCodium/vscodium/commit/16eb6e4c833b2b1cb02509f963ed18a70919c4a0 fixed macOS & Linux checks.

 To convert the LICENSE file on the fly we can use [pandoc](https://pandoc.org/).

**Comment by daiyam** [comment]
@alexhass Thanks for the PR but are you planning the finish it?

**Comment by alexhass** [comment]
What do you mean? It is finished.

**Comment by michalzobec** [comment]
so, when we can expect MSI packages?

**Comment by daiyam** [comment]
@alexhass Can you add it to the github workflow [.github/workflows/windows.yml](https://github.com/VSCodium/vscodium/blob/master/.github/workflows/windows.yml) to generate the following `msi`:

- VSCode-ia32-[VERSION].msi
- VSCode-x64-[VERSION].msi

For the updates disabled binaries, maybe `msi` like are good:

- VSCode-ia32-noupdate-[VERSION].msi
- VSCode-x64-noupdate-[VERSION].msi

(with the suffix `noupdate` or anything better)

**Comment by pmahend1** [comment]
- Codium-ia32-[VERSION].msi
- Codium-x64-[VERSION].msi

and for binaries with no-updates I personally prefer `Codium-[Processor-Arch]-updates-disabled-[Version].msi`

**Comment by daiyam** [comment]
@pmahend1 Yep. I like your suggestion. I will go with `VSCodium-[Processor-Arch]-updates-disabled-[Version].msi`.

**Comment by GitMensch** [comment]
Current TODO list here (most in https://github.com/VSCodium/vscodium/tree/bd85701f35308b7b1ecba429a2b7162321ba6ad7/build/wix/Resources):

- [ ] optional: remove the LICENSE.rtf creating it on the fly from LICENSE (note from the [docs](https://wixtoolset.org//documentation/manual/v3/wixui/wixui_customizations.html): must be rtf, can also be specified as command line option)
- [ ] remove code.ico: adjust the path in the configuration and ideally prepare for insider builds by using a different icon, for both options see [PowerShell Example](https://github.com/PowerShell/PowerShell/blob/af6d9fbe141848d14c17528c9b6becf0e81c713e/assets/Product.wxs#L8)
- [ ] replace wix-banner.bmp and wix-dialog.bmp using the "new" icon and switching to PNG format (which obviously works there as seen in the PowerShell example [note: the dialog one which they use is quite cool, as we don't have something like that we could either increase the symbol as in the main README.md or add a screenshot])
- [ ] add to https://github.com/VSCodium/vscodium/blob/master/.github/workflows/windows.yml as `VSCodium-[Processor-Arch]-updates-disabled-[Version].msi`

**Comment by daiyam** [comment]
@GitMensch Thx! The todo list is useful. Do you want to finish it?

**Comment by GitMensch** [comment]
> Do you want to finish it?

Psst, don't tell anyone but I haven't build Codium locally and don't have WiX installed... ;-)

I could give it a try in some weeks (using CI only), but hope that the TODO list and references may help someone to get it done before the next release.

**Comment by daiyam** [comment]
@GitMensch the next release is this Wednesday or Thursday, so it will be short.

**Comment by daiyam** [comment]
This PR has been integrated into #827 and has been merged.

**Pull request closed without merging**
