### PR TITLE
docs: fix environment variable names for user-specific product.json

### PR DESCRIPTION
**Pull request by GitMensch**
follow-up to 0ead786b6c1608c414a383e1850484e8f38c1872

### CODE REVIEW

**Comment by stripedpajamas** [comment]
Is this still accurate? If so can you resolve the conflicts?

**Comment by daiyam** [comment]
I believe the doc has been updated and the paths are new correct.

**Comment by daiyam** [comment]
`%USERPROFILE%\AppData\Roaming\VSCodium` is correct: https://github.com/microsoft/vscode/blob/9520f0a515e7e24802c92f885a0efb242fca3831/src/vs/platform/environment/node/userDataPath.js#L77

**Comment by daiyam** [comment]
I find the Linux section has a bit too much verboseness.

**Comment by daiyam** [comment]
@GitMensch I believe we should close this PR.

**Comment by GitMensch** [comment]
> I believe we should close this PR.

Done, if anyone finds that there is something to improve in the docs: please do it.

**Pull request closed without merging**
